name: Cache dbt deps

on:
  push:
    branches:
      - main

env:
  DBT_PROFILES_DIR: ./
  TARGET: CI
  SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
  SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
  SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}

jobs:

  cache:
    name: Cache dbt deps
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Cache DBT Dependencies
        id: cache-dbt-deps
        uses: actions/cache@v2
        with:
          path: ./dbt_modules/
          key: dbt-deps-${{ hashFiles('**/packages.yml') }}
          restore-keys: |
            dbt-deps-

      - name: DBT deps
        uses: mwhitaker/dbt-action@master
        with:
          dbt_command: "dbt deps"
        if: steps.cache-dbt-deps.outputs.cache-hit != 'true'
